### ISSUE TITLE
Upgrade to Storybook 8 and Angular 18

### ISSUE THREAD

**Issue by andrewalderson** [storybookjs/testing-angular#5]
Is there a plan or a timeline to upgrade this library to Storybook 8 so it supports Angular 18?

I could submit a PR to upgrade this repo to Storybook 8 but I have been wondering why this is in a separate repo and not in the main storybook repo. All of the snippets in the [Storybook docs](https://storybook.js.org/docs/writing-tests/stories-in-unit-tests) have a link requesting a PR for adding this functionality to the main storybook repo.

**Comment by Marklb** [comment]
Yes, I will get this updated. I think it just needs the dependencies updated, but shouldn't be to much trouble to fix if the code needs changed.

Most of the work is handled by the main repo's code now anyway, since I was able to strip out a lot in the update to Storybook 7. I just wrap the compose methods to workaround a feature that was removed, but sort of relied on in this library. Then the renderer is just a copy of the main repo's renderer with only what is needed to update args. So, I will also look into getting it moved. It would probably be maintained better that way, instead of relying on myself to keep this one updated.

**Comment by Marklb** [comment]
I want to test a few more scenarios and see if I can fix some minor issues I had with types, but I published a version that should work on Storybook 8 and Angular 18. `@storybook/testing-angular@1.0.3-next.0`

**Comment by andrewalderson** [comment]
I can confirm that this now works with Angular 18. Thank you.

**Comment by andrewalderson** [comment]
I think I spoke too soon. The ```composeStories``` method doesn't seem to like it if components have signal inputs. Storybook itself works fine but you can't import all of the stories together. The work around is to compose each story individually. I have a repo that I was just updating to Angular 18. You can look at this [test file](https://github.com/andrewalderson/angular-material-avatar/blob/main/packages/material/avatar/src/lib/avatar.component.cy.ts) if you want to see a sample of the problem. I will do a little more investigating this weekend if I get a chance.

**Comment by Marklb** [comment]
@andrewalderson That error is one of the reasons I only published a `next`. That should just be a types issue. The code should work if you used `as any`, but that shouldn't be necessary and isn't good.

I think I have it fixed, in the `next` branch, but the auth token that was being used for publishing this package to NPM may have expired. That usually gets resolved fairly quick, so it should be published soon.

**Comment by Marklb** [comment]
I just published `@storybook/testing-angular@1.0.3-next.1`, which should have the `composeStories` types fixed. If I don't see any other issues then I will publish it to `latest` this week.

**Comment by andrewalderson** [comment]
I can confirm that this works as expected now

**Comment by Marklb** [comment]
`@storybook/testing-angular@1.0.3` is published.
